/*
 * ATCommands.h
 *
 *  Created on: Aug 9, 2024
 *      Author: Owner
 */

#ifndef INC_ATCOMMANDS_H_
#define INC_ATCOMMANDS_H_

#define AT_SET_DEVEUI 		"AT+DEUI=70:DD:CC:BB:AA:DD:DD:DD\r\n"
#define AT_SET_APPEUI 		"AT+APPEUI=01:01:01:01:01:01:01:01\r\n"
#define AT_SET_APPKEY 		"AT+APPKEY=AA:BB:CC:30:90:69:12:33:5B:76:E7:AC:32:3D:2D:1D\r\n"
#define AT_SET_NWKKEY 		"AT+NWKKEY=AA:BB:CC:30:90:69:12:33:5B:76:E7:AC:32:3D:2D:1D\r\n"
#define AT_SET_APPSKEY 		"AT+APPSKEY=AA:BB:CC:30:90:69:12:33:5B:76:E7:AC:32:3D:2D:1D\r\n"
#define AT_SET_NWKSKEY 		"AT+NWKSKEY=AA:BB:CC:30:90:69:12:33:5B:76:E7:AC:32:3D:2D:1D\r\n"
#define AT_SET_ADR       	"AT+ADR=0\r\n"
#define AT_SAVE_TO_FLASH 	"AT+CS\r\n"
#define AT_RST_MCU 		    "ATZ\r\n"

#define AT_JOIN_OTAA   		"AT+JOIN=1\r\n"
#define AT_ADR_DISABLE   	"AT+ADR=0\r\n"
#define AT_ADR_ENABLE   	"AT+ADR=1\r\n"
//#define AT_SEND_            "AT+SEND=1:0:"

typedef enum{
	UART_IDLE = 0,
	AT_RESPONSE_CAPTURE_OK,
	AT_RESPONSE_CAPTURE_NVM_STORED,
	AT_RESPONSE_CAPTURE_RESET,
	AT_RESPONSE_CAPTURE_JOIN,
	AT_RESPONSE_CAPTURE_SEND_OK

}LPUARTState;



#endif /* INC_ATCOMMANDS_H_ */
